language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: cCVhsfInMKMbfc46cof3IuxkYvs0KjsOZVv9VioLCppZA/Fy+bmJx0hOJwRDGgSWipEo/OrPo8DlUKgIL3zyiAFyfDRIYn9jK3waLI6U6S0YueztknnjAUzIOt9hD7b4hQgzeiTELI29sUL0qlWKSMCcMYQzq7Ltn8emMR0BYQ4=
  app: node-web-example
  on:
    repo: apipkin/node-web-example
